### PR TITLE
Change init params to inherited, fixes #23

### LINKED ISSUE #23: Bring params into standard pattern
Params in this module are not currently using standard pattern of class inheritance.  PR will fix this.

### PR DESCRIPTION
**Pull request by siliconalchemy**
Change init.pp to inherit params.  Also check if $::puppetmaster variable is defined to get rid of warning on puppetmaster.

### CODE REVIEW

**Comment by siliconalchemy** [comment]
Further addresses #5

**Comment by bzed** [comment]
Could you rebase it on my last commit? Would be great. Thanks a lot!

**Comment by siliconalchemy** [comment]
Erm, does that look sane?  I'll be honest I have no idea what I'm doing in git, I did some random commands from a PR guide to try and rebase:
https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by bzed** [comment]
You've merge it, not rebased it. Just did it and pushed it :) Thanks!

**Pull request closed without merging**
