### PR TITLE
Add script to check if alternative subjects (DNS) has changed

### PR DESCRIPTION
**Pull request by derdanne**
update $le_check_command to fail if alternative subject changed for renewing certificate

### CODE REVIEW

**Comment by bzed** [comment]
Thanks for the patch! Before I'll accept it, I'm wondering if it is necessary at all - in theory replacing the .csr file shoudl retrieve a new certificate. What am I missing here?

The rather buggy part is that the csr file is not being recreated on the client if the key file was replaced. There is a notification missing in the openssl module.

**Comment by derdanne** [comment]
Hey,

the CSRs are renewed, but the certificates weren't re-requested, because this

`$le_check_command = join([
        "/usr/bin/test -f ${crt_file}",
        "/usr/bin/openssl x509 -checkend 2592000 -noout -in ${crt_file}",
    ], ' && ')`

will always be true, when the certificate isn't older than -checkend parameter. So the "create-certificate-${domain}" won't be executed unless $le_check_command fails.

Or am i missing something here?

**Review by bzed — CHANGES_REQUESTED** [review]
I see several problems in files/letsencrypt_check_altnames.sh:
- there are bashisms used, although not necessary, for example if foo | bar works perfectly fine without [[ ]]. (yes, the other scripts have /bin/bash in their header, but they would just work fine with /bin/sh and need to be fixed not to require bash)
- running openssl for every domainname on the crt is slow, its much faster to generate a lists of domains from the csr and crt and diff them. you also might want to renew the cert when it has more domains than the csr. This case is not handled by your code.

**Comment by derdanne** [comment]
Ah, i see you've added a check to compare creation time of csr and crt. This should also do it. I prefer a solution to compare DNS in csr and crt, because you can manipulate the creation time via touch.

**Comment by bzed** [comment]
That looks better, thanks for the change! If you don't mind I don't merge it right now because I want to rename to module before the letsencrypt trademark enforcement people ask me to do so, unfortunately they need to be strict about it as stupid other companies try to abuse the name :(

**Review by bzed — APPROVED** [review]

**Pull request merged**
